### PR TITLE
built chat app

### PR DESCRIPTION
**Pull request by DrewStableBoi**
Alright guys, this is a big one. Be sure to look through it, although there shouldn't be any conflicts with the base branch. The way it works is this:

1. When a user creates an account on our app, they'll simultaneously create a chat user as well
2. The React Library being used for this is called Chatkit. Docs here: https://pusher.com/docs/chatkit
3. There's a button that just allows people to enter chat, when they click it it should direct them to the chat window, where they'll see a list of people online, as well as the chat window. 
4. Right now, there's just one public room, and a list of who's online. There is also an indicator telling you who is typing. We should test this tomorrow. 

There you go! Let me know if you have questions.

### CODE REVIEW

**Review by Paulyg15 — COMMENTED** [review]
@DrewStableBoi , Looks good man! The only thing, is there a reason for not creating functions in the controller file for the user_chat and chat_room endpoints?

**Comment by DrewStableBoi** [comment]
> @DrewStableBoi , Looks good man! The only thing, is there a reason for not creating functions in the controller file for the user_chat and chat_room endpoints?

**Comment by DrewStableBoi** [comment]
@Paulyg15 I did that just to differentiate the chat endpoints from the others. No particular reason other than that.

**Comment by Paulyg15** [comment]
@DrewStableBoi , I guess that's fine.

**Pull request merged**
